### ISSUE TITLE
possible bug in riak_core_vnode.erl for vnode_coverage.

### ISSUE THREAD

**Issue by RomanShestakov** [basho/riak_core#342] opened 2013-06-22 13:12 UTC
I think there a possible bug in riak_core_vnode.erl for vnode_coverage.
1. reply function defined as following:

reply({server, Ref, From}, Reply) ->
    riak_core_send_msg:reply_unreliable(From, {Ref, Reply});
reply({raw, Ref, From}, Reply) ->
1. but in riak_core_send_msg.erl function riak_core_send_msg:reply_unreliable has in-compatible with this call signature:

reply_unreliable({To, Tag}, Reply) ->
    bang_unreliable(To, {Tag, Reply}).

it expects tuple instead of pid()

here is the simple example to replicate the err.:
1. add the following  function:

ping_all() ->
    DocIdx = riak_core_util:chash_key({<<"ping">>, term_to_binary(now())}),
    PrefList = riak_core_apl:get_apl(DocIdx, num_partitions_in_ring(), magma),
    riak_core_vnode_master:coverage (ping,
                     PrefList,
                     all,
                     {server, erlang:make_ref(), self()},
                     magma_vnode_master).

num_partitions_in_ring() ->
    riak_core_ring:num_partitions(riak_core_ring:fresh()).
1.  and the following to vnode:
   handle_coverage(ping, _KeySpaces, _Sender, State) ->
   ?PRINT({pong, State#state.partition}),
   {reply, {pong, State#state.partition}, State};
2. magma:ping_all().

18:07:30.950 [error] CRASH REPORT Process <0.341.0> with 0 neighbours exited with reason: no function clause matching riak_core_send_msg:reply_unreliable(<0.301.0>, {{#Ref<0.0.0.1477>,{296867520082839655260123481645494988367611297792,'magma@127.0.0.1'}},{pong,296867520082839655260123481645494988367611297792}}) line 40 in gen_fsm:terminate/7 line 611
18:07:30.950 [error] gen_fsm <0.343.0> in state active terminated with reason: no function clause matching riak_core_send_msg:reply_unreliable(<0.301.0>, {{#Ref<0.0.0.1477>,{319703483166135013357056057156686910549735243776,'magma@127.0.0.1'}},{pong,319703483166135013357056057156686910549735243776}}) line 40

Regards, Roman

**Comment by jrwest** [comment] 2013-06-23 20:26
There does seem to be a slight issue here. A quick reproduction w/o `riak_core` running:

```
riak_core_vnode:reply({server, undefined, self()}, hi).
** exception error: no function clause matching riak_core_send_msg:reply_unreliable(<0.466.0>,hi) (src/riak_core_send_msg.erl, line 40)
```

However, `riak_core`  uses this sender "reference" (not erlang `reference()` -- the tuple itself) via `riak_core_vnode_master:sync_command/3,4`, which creates a tuple of the form `{server, undefined, {pid(), reference()}` [1]. This works fine w/ `riak_core_vnode:reply/2`. Other uses of `reply/2` in Riak use fsms which aren't affected by this.

```
(riak@127.0.0.1)1> riak_core_vnode:reply({server, undefined, {self(), make_ref()}}, hi).
{#Ref<0.0.0.4423>,hi}
(riak@127.0.0.1)2> receive {Ref, hi} -> Ref end.
#Ref<0.0.0.4423>
```

There does seem to be some change in semantics here that was probably introduced as part of #299. For now, a quick fix would be to change `{server, make_ref(), self()}` to `{server, undefined, {self(), make_ref()}}`. Unfortunately `{server, make_ref(), {self(), make_ref()}}` now makes little sense (at least to me) -- see below. We will discuss internally on the best way to fix and update this issue:

```
(riak@127.0.0.1)1> riak_core_vnode:reply({server, make_ref(), {self(), make_ref()}}, hi).
{#Ref<0.0.0.3722>,{#Ref<0.0.0.3721>,hi}}
(riak@127.0.0.1)2> receive A -> A end.
{#Ref<0.0.0.3722>,{#Ref<0.0.0.3721>,hi}}
```

cc/ @slfritchie 

[1] https://github.com/basho/riak_core/blob/master/src/riak_core_vnode_master.erl#L250-L253

**Comment by jrwest** [comment] 2013-06-23 20:37
Another workaround, which actually may be more proper in this case, is to use `{raw, make_ref(), self()}` as the process expecting the message is neither a `gen_server` or `gen_fsm`. This also works in my testing.

**Comment by slfritchie** [comment] 2013-06-24 07:48
The formatting of the `To` and `Tag` parts of the reply function are dictated by the OTP messaging patterns and not by Riak Core.  I thought that I had honored the OTP pattern correctly, but I could be wrong.  Today is full of meetings and impossible to concentrate ... I'll look at this matter later this week when I have some time for my brain to re-load all of the memories that have been sent to secondary storage.

**Comment by slfritchie** [comment] 2013-07-03 16:10
Sorry, I still haven't had time to examine this issue in detail.

@RomanShestakov, can you please create a compilable & executable source module that demonstrates the bug?  In the examples that I see in the riak_kv app, the `{raw, ...}` form is used.  And in the riak_core app, the `{fsm, ...}` form is used.
- https://github.com/basho/riak_kv/blob/master/src/riak_kv_pipe_index.erl#L72
- https://github.com/basho/riak_kv/blob/master/src/riak_kv_pipe_listkeys.erl#L77
- https://github.com/basho/riak_core/blob/master/src/riak_core_coverage_fsm.erl#L228

**Comment by jrwest** [comment] 2013-07-09 03:38
@slfritchie just to clarify: the issue isn't its use in Riak but that `riak_core` previously supported the `{server, reference(), pid()}` format. But fwiw, the newly supported form of `{server, ...}` is used [here](https://github.com/basho/riak_core/blob/master/src/riak_core_vnode_master.erl#L259)

**Comment by slfritchie** [comment] 2013-09-27 10:11
Time for some belated repo curating ... @jrwest The form of `From` that you mention [here](https://github.com/basho/riak_core/blob/master/src/riak_core_vnode_master.erl#L259) is not a bare pid: it's a {reference(), pid()} wrapped thingie from gen_server:call(), and AFAIK it works just fine.  Or am I missing something too obvious to be seen on Friday evening?

**Comment by jrwest** [comment] 2013-09-27 17:44
@slfritchie hopefully i remember this correctly, but the point was `{server, undefined, pid()}` no longer works. In our case like you said it becomes a `{reference(), pid()}` so its fine. But this broke riak_core apps for others because `{server, undefined, pid()}` is not uncommon to use for some folks.

**Comment by jrwest** [comment] 2014-03-24 16:49
unfortunately, given this has straggled for a while and seems like there won't be a fix coming, I'm going to close this out. While this did break backwards compatibility, there is a known workaround (see https://github.com/basho/riak_core/issues/342#issuecomment-19880592). If we revisit or a community member has a fix, I would be glad to re-open.

**Closed as completed by jrwest** 2014-03-24 16:49 UTC
