### ISSUE TITLE
Intermittent crash on startup

### ISSUE THREAD

**Issue by jonmeredith** [basho/riak_core#227] opened 2012-09-11 18:37 UTC
Intermittent crash on startup - 6 node cluster, 32 vnodes.

```
 {"Kernel pid terminated",application_controller,"{application_start_failure,riak_core,{bad_return,{{riak_core_app,start,[normal,[]]},{'EXIT',{{function_clause,[{orddict,fetch,['riak@mgmt.r1s15',[{'riak@mgmt.r1s16',[{{riak_core,staged_joins},[true,false]},{{riak_core,vnode_routing},[proxy,legacy]}]}]],[{file,[111,114,100,100,105,99,116,46,101,114,108]},{line,72}]},{riak_core_capability,renegotiate_capabilities,1,[{file,[115,114,99,47,114,105,97,107,95,99,111,114,101,95,99,97,112,97,98,105,108,105,116,121,46,101,114,108]},{line,417}]},{riak_core_capability,handle_call,3,[{file,[115,114,99,47,114,105,97,107,95,99,111,114,101,95,99,97,112,97,98,105,108,105,116,121,46,101,114,108]},{line,216}]},{gen_server,handle_msg,5,[{file,[103,101,110,95,115,101,114,118,101,114,46,101,114,108]},{line,588}]},{proc_lib,init_p_do_apply,3,[{file,[112,114,111,99,95,108,105,98,46,101,114,108]},{line,227}]}]},{gen_server,call,[riak_core_capability,{register,{riak_core,vnode_routing},{capability,[proxy,legacy],legacy,{riak_core,legacy_vnode_routing,[{true,legacy},{false,proxy}]}}},infinity]}}}}}}"}
```

**Comment by evanmcc** [comment] 2013-08-09 21:02
Is this not the mismatched nodename issue?

**Comment by slfritchie** [comment] 2013-09-27 08:15
@evanmcc Time for some belated repo curating ... "mismatched" meaning changing vm.args while leaving behind an old ring with a different node name?  Or something else?

Looking at a recent'ish version of riak_core_capability:renegotiate_capabilities() ... if the orddict:fetch is a orddict:find() instead, and if find doesn't find it, then ... do what the first func clause does, i.e., nothing?

**Comment by jrwest** [comment] 2014-03-24 17:01
this is a known nodename mismatch issue and duplicate of both https://github.com/basho/riak_core/pull/266 and https://github.com/basho/riak_core/pull/244. closing.

**Closed as completed by jrwest** 2014-03-24 17:01 UTC
