### ISSUE TITLE
configurable handoff sender

### ISSUE THREAD

**Issue by yrashk** [basho/riak_core#157] opened 2012-03-22 23:52 UTC
Hi,

I was wondering whether you would consider a patch that would make handoff sender configurable, that is to allow different ways for handoffs to be collected and sent.

**Comment by jonmeredith** [comment] 2012-03-28 14:16
Hi Yuri - sorry for taking a while to get back to you. 

Configurable in what sense?  Setting a callback for a different handler mechanism instead of the default one?  

We've been talking internally about changing the handoff sender/receiver to have a better defined interface into the vnode itself, for example allowing you to keep an accumulator in the handoff receiver callback so you could have a more flexible sender format.  That would be helpful for search which streams lists of index / field / term / docid where there are many docids for each term and many terms for each field and many fields in an index.  At the moment we sent the objects in big lumps of multiple docids but it would be better if we could do things more incrementally.

 I think you're meeting with Joe while at EF - that may be a good place to talk through what you'd like to do.

**Comment by yrashk** [comment] 2012-03-28 18:08
Yeah, I meant setting a different handler mechanism instead of the default one :) Anyway, I am looking forward to that meeting that we've scheduled. I guess this will help me understanding priorities better

**Comment by jonmeredith** [comment] 2012-03-28 18:59
Pull requests always considered - it's a sensitive area of code, but perhaps there are some structural changes we could make to make what you want work cleanly.

Out of interest, what would the new handler mechanism need to do?  Is it something that would be better generalized as part of the existing mechanism?

The riak_core:register function is probably a good way to specify the module to use for the app, but there are still going to be  some fiddling around to do with the handoff manager/handoff_sender_sup/handoff_receiver_sup.

**Comment by rzezeski** [comment] 2012-08-22 16:14
@yrashk Did you explore this further?  Is this still something you need?

**Comment by rzezeski** [comment] 2012-08-28 16:26
I'm going to close this.  I've spent a considerable amount of time in the handoff code.  I'm of the opinion that it could use an entire overhaul.  Some things I would like to see are a more flexible protocol, pluggable encoding, iterative/pausable folding over the vnode data rather than passing a function to the vnode (which is the cause for some very awkward code).  Perhaps the entire idea of a sender can be made into a behavior and be configurable per service but I haven't given it much thought and am not sure what it would look like.  If you think of something concrete a PR would be great.

**Closed as completed by rzezeski** 2012-08-28 16:26 UTC
